app:
  name: wconn
  pinglist: "4.2.2.2,4.2.2.3"
  delaybet: 4s
  pingcount: 9
  save: true
tsdb:
  host: 192.168.0.139
  port: 4242
  defaultBuffer: 1
  defaultInterval: 1
  metric: wconn
  http:
    dialTimeout: 3s
    tlsHandShakeTimeout: 3s
    maxIdleConnsPerHost: 20
    maxIdleConns: 20
    idleConnTimeout: 2m 
    clientTimeout: 5s 
